import { NextResponse } from 'next/server'
import { Product } from '@/lib/types'

const MOCK_PRODUCTS: Product[] = [
  {
    id: 'artemis-mini',
    name: 'ARTEMIS Mini',
    slug: 'artemis-mini',
    priceFrom: 1200000,
    images: ['/images/products/mini-1.svg', '/images/products/mini-2.svg'],
    specs: {
      waterproof: 'IP67',
      battery: '400mAh - 3-5 ngày',
      gps: true,
      simCard: true,
      weight: '35g',
    },
    description: 'Vòng tay thông minh nhỏ gọn, phù hợp cho trẻ 3-8 tuổi. Tích hợp GPS/LBS, gọi thoại 2 chiều, và SOS khẩn cấp.',
    features: [
      'Định vị GPS/LBS chính xác',
      'Gọi thoại 2 chiều',
      'Nút SOS khẩn cấp',
      'Chống nước IP67',
      'Pin 3-5 ngày',
      'Thiết kế nhẹ, thoải mái',
    ],
  },
  {
    id: 'artemis-active',
    name: 'ARTEMIS Active',
    slug: 'artemis-active',
    priceFrom: 1800000,
    images: ['/images/products/active-1.svg', '/images/products/active-2.svg'],
    specs: {
      waterproof: 'IP68',
      battery: '500mAh - 5-7 ngày',
      gps: true,
      simCard: true,
      weight: '42g',
    },
    description: 'Phiên bản cao cấp với GPS 4G, camera, và chống nước IP68. Lý tưởng cho trẻ năng động 6-12 tuổi.',
    features: [
      'GPS 4G tốc độ cao',
      'Camera chụp ảnh từ xa',
      'Chống nước IP68 (bơi lội)',
      'Đếm bước, nhắc uống nước',
      'Pin 5-7 ngày',
      'Màn hình màu cảm ứng',
    ],
  },
  {
    id: 'artemis-pro',
    name: 'ARTEMIS Pro',
    slug: 'artemis-pro',
    priceFrom: 2400000,
    images: ['/images/products/pro-1.svg', '/images/products/pro-2.svg'],
    specs: {
      waterproof: 'IP68',
      battery: '600mAh - 7-10 ngày',
      gps: true,
      simCard: true,
      weight: '48g',
    },
    description: 'Phiên bản cao cấp nhất với GPS 5G, video call, AI nhận dạng, và nhiều tính năng thông minh. Dành cho trẻ 8-15 tuổi.',
    features: [
      'GPS 5G siêu chính xác',
      'Video call HD 2-way',
      'AI phát hiện ngã/va chạm',
      'Màn hình AMOLED cảm ứng',
      'Pin 7-10 ngày',
      'Sạc không dây',
      'Theo dõi sức khỏe nâng cao',
    ],
  },
  {
    id: 'artemis-lite',
    name: 'ARTEMIS Lite',
    slug: 'artemis-lite',
    priceFrom: 899000,
    images: ['/images/products/lite-1.svg', '/images/products/lite-2.svg'],
    specs: {
      waterproof: 'IP65',
      battery: '350mAh - 2-4 ngày',
      gps: true,
      simCard: false,
      weight: '28g',
    },
    description: 'Phiên bản giá rẻ, nhẹ nhàng cho trẻ nhỏ 3-6 tuổi. GPS cơ bản, SOS, không cần SIM card.',
    features: [
      'GPS/LBS cơ bản',
      'Nút SOS một chạm',
      'Kết nối Bluetooth với điện thoại',
      'Siêu nhẹ chỉ 28g',
      'Giá cả phải chăng',
      'Dễ sử dụng',
    ],
  },
  {
    id: 'artemis-sport',
    name: 'ARTEMIS Sport',
    slug: 'artemis-sport',
    priceFrom: 1650000,
    images: ['/images/products/sport-1.svg', '/images/products/sport-2.svg'],
    specs: {
      waterproof: 'IP68',
      battery: '550mAh - 6-8 ngày',
      gps: true,
      simCard: true,
      weight: '40g',
    },
    description: 'Thiết kế thể thao năng động, theo dõi hoạt động thể chất. Chống va đập, phù hợp trẻ 7-14 tuổi yêu thích vận động.',
    features: [
      'Theo dõi hoạt động thể thao',
      'Đếm bước, calo, quãng đường',
      'Chống va đập, chống nước IP68',
      'Đo nhịp tim liên tục',
      'Chế độ thể thao đa dạng',
      'Khung viền siêu bền',
    ],
  },
  {
    id: 'artemis-princess',
    name: 'ARTEMIS Princess',
    slug: 'artemis-princess',
    priceFrom: 1550000,
    images: ['/images/products/princess-1.svg', '/images/products/princess-2.svg'],
    specs: {
      waterproof: 'IP67',
      battery: '450mAh - 4-6 ngày',
      gps: true,
      simCard: true,
      weight: '36g',
    },
    description: 'Thiết kế đặc biệt cho bé gái với màu sắc pastel, họa tiết công chúa, unicorn. Đầy đủ tính năng an toàn. Độ tuổi 4-10.',
    features: [
      'Thiết kế công chúa độc quyền',
      'Màu sắc pastel dịu nhẹ',
      'GPS an toàn chính xác',
      'Gọi thoại rõ ràng',
      'Kèm charm unicorn & công chúa',
      'Hộp quà sang trọng',
    ],
  },
  {
    id: 'artemis-explorer',
    name: 'ARTEMIS Explorer',
    slug: 'artemis-explorer',
    priceFrom: 1950000,
    images: ['/images/products/explorer-1.svg', '/images/products/explorer-2.svg'],
    specs: {
      waterproof: 'IP68',
      battery: '580mAh - 6-9 ngày',
      gps: true,
      simCard: true,
      weight: '44g',
    },
    description: 'Dành cho trẻ thích phiêu lưu và khám phá. Tích hợp la bàn, nhiệt kế, cao độ kế. Thiết kế bền bỉ. Độ tuổi 8-14.',
    features: [
      'La bàn điện tử tích hợp',
      'Nhiệt kế & cao độ kế',
      'GPS kép (GPS + GLONASS)',
      'Chống sốc quân đội',
      'Đèn pin LED tích hợp',
      'Chế độ ngoài trời',
    ],
  },
  {
    id: 'artemis-teen',
    name: 'ARTEMIS Teen',
    slug: 'artemis-teen',
    priceFrom: 2100000,
    images: ['/images/products/teen-1.svg', '/images/products/teen-2.svg'],
    specs: {
      waterproof: 'IP68',
      battery: '620mAh - 7-10 ngày',
      gps: true,
      simCard: true,
      weight: '46g',
    },
    description: 'Thiết kế trưởng thành cho teen 13-18 tuổi. Màn hình lớn, nhiều ứng dụng, vẫn giữ tính năng an toàn cho phụ huynh.',
    features: [
      'Thiết kế trẻ trung, hiện đại',
      'Màn hình 1.4 inch cảm ứng',
      'Thông báo mạng xã hội',
      'Thanh toán điện tử',
      'Chế độ riêng tư cho teen',
      'GPS bảo mật cao',
    ],
  },
  {
    id: 'artemis-baby',
    name: 'ARTEMIS Baby',
    slug: 'artemis-baby',
    priceFrom: 799000,
    images: ['/images/products/baby-1.svg', '/images/products/baby-2.svg'],
    specs: {
      waterproof: 'IP65',
      battery: '300mAh - 2-3 ngày',
      gps: true,
      simCard: false,
      weight: '25g',
    },
    description: 'Dành cho trẻ sơ sinh đến 3 tuổi. Siêu nhẹ, an toàn tuyệt đối, chất liệu y tế. Giám sát vị trí qua Bluetooth.',
    features: [
      'Siêu nhẹ chỉ 25g',
      'Chất liệu an toàn cho da trẻ',
      'Bluetooth tracking',
      'Cảm biến nhiệt độ',
      'Thiết kế đáng yêu',
      'Không cần SIM card',
    ],
  },
  {
    id: 'artemis-smart',
    name: 'ARTEMIS Smart',
    slug: 'artemis-smart',
    priceFrom: 1750000,
    images: ['/images/products/smart-1.svg', '/images/products/smart-2.svg'],
    specs: {
      waterproof: 'IP67',
      battery: '500mAh - 5-7 ngày',
      gps: true,
      simCard: true,
      weight: '42g',
    },
    description: 'Phiên bản thông minh với trợ lý AI, nhận diện giọng nói, dịch thuật tức thì. Độ tuổi 8-14.',
    features: [
      'Trợ lý AI tích hợp',
      'Nhận diện giọng nói',
      'Dịch thuật đa ngôn ngữ',
      'Tính năng học tập',
      'Nhắc nhở thông minh',
      'GPS chính xác cao',
    ],
  },
  {
    id: 'artemis-adventure',
    name: 'ARTEMIS Adventure',
    slug: 'artemis-adventure',
    priceFrom: 1850000,
    images: ['/images/products/adventure-1.svg', '/images/products/adventure-2.svg'],
    specs: {
      waterproof: 'IP68',
      battery: '600mAh - 7-9 ngày',
      gps: true,
      simCard: true,
      weight: '45g',
    },
    description: 'Dành cho trẻ năng động thích phiêu lưu. Chống sốc cực mạnh, nhiều cảm biến ngoài trời. Độ tuổi 9-15.',
    features: [
      'Khung nhôm chống sốc',
      'Đèn LED 3 chế độ',
      'Cảm biến nhiệt độ & độ cao',
      'La bàn điện tử',
      'SOS khẩn cấp nâng cao',
      'Chế độ sinh tồn',
    ],
  },
  {
    id: 'artemis-fashion',
    name: 'ARTEMIS Fashion',
    slug: 'artemis-fashion',
    priceFrom: 1650000,
    images: ['/images/products/fashion-1.svg', '/images/products/fashion-2.svg'],
    specs: {
      waterproof: 'IP67',
      battery: '480mAh - 5-7 ngày',
      gps: true,
      simCard: true,
      weight: '38g',
    },
    description: 'Thiết kế thời trang cao cấp, dây da cao cấp có thể thay đổi. Phù hợp cho cả trẻ và người lớn. Độ tuổi 10+.',
    features: [
      'Thiết kế thời trang sang trọng',
      'Dây da cao cấp thay được',
      'Nhiều màu sắc trendy',
      'Viền kim loại sang',
      'Màn hình cảm ứng đẹp',
      'Tính năng đầy đủ',
    ],
  },
]

export async function GET() {
  return NextResponse.json(MOCK_PRODUCTS)
}

