import { NextResponse } from 'next/server'
import { Product } from '@/lib/types'

const MOCK_PRODUCTS: Product[] = [
  {
    id: 'bunny-baby-pink',
    name: 'ARTEMIS Bunny Baby Pink',
    slug: 'bunny-baby-pink',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/templates/bunny-baby-pink.png'],
    specs: {
      waterproof: 'IP67',
      battery: '400mAh - 3-5 ngày',
      gps: true,
      simCard: true,
      weight: '35g',
    },
    description: 'Thỏ hồng đáng yêu với họa tiết hoa và tim, dành cho bé gái năng động. Thiết kế độc quyền với màu hồng pastel ngọt ngào.',
    features: [
      'Định vị GPS/LBS chính xác',
      'Thiết kế Bunny độc quyền',
      'Họa tiết hoa & tim đáng yêu',
      'Chống nước IP67',
      'Pin 3-5 ngày',
      'Màu hồng pastel dịu nhẹ',
    ],
  },
  {
    id: 'bunny-lavender',
    name: 'ARTEMIS Bunny Lavender',
    slug: 'bunny-lavender',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/templates/bunny-lavender.png'],
    specs: {
      waterproof: 'IP67',
      battery: '400mAh - 3-5 ngày',
      gps: true,
      simCard: true,
      weight: '35g',
    },
    description: 'Thỏ tím pastel với họa tiết chấm tròn đầy màu sắc, dễ thương và sáng tạo. Phù hợp cho bé yêu thích sự độc đáo.',
    features: [
      'Định vị GPS/LBS chính xác',
      'Thiết kế Bunny sáng tạo',
      'Họa tiết chấm tròn đa màu',
      'Chống nước IP67',
      'Pin 3-5 ngày',
      'Màu tím lavender trendy',
    ],
  },
  {
    id: 'bunny-yellow',
    name: 'ARTEMIS Bunny Yellow',
    slug: 'bunny-yellow',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/templates/bunny-yellow.png'],
    specs: {
      waterproof: 'IP67',
      battery: '400mAh - 3-5 ngày',
      gps: true,
      simCard: true,
      weight: '35g',
    },
    description: 'Thỏ vàng tươi với cà rốt và lá, năng lượng tích cực cho bé. Thiết kế tràn đầy sức sống và vui tươi.',
    features: [
      'Định vị GPS/LBS chính xác',
      'Thiết kế Bunny năng động',
      'Họa tiết cà rốt & lá cây',
      'Chống nước IP67',
      'Pin 3-5 ngày',
      'Màu vàng cam tươi sáng',
    ],
  },
  {
    id: 'bunny-mint',
    name: 'ARTEMIS Bunny Mint',
    slug: 'bunny-mint',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/templates/bunny-mint.png'],
    specs: {
      waterproof: 'IP67',
      battery: '400mAh - 3-5 ngày',
      gps: true,
      simCard: true,
      weight: '35g',
    },
    description: 'Thỏ xanh mint tươi mát với họa tiết lá và hoa, thanh lịch và dịu dàng. Màu sắc dễ chịu cho mắt.',
    features: [
      'Định vị GPS/LBS chính xác',
      'Thiết kế Bunny thanh lịch',
      'Họa tiết lá & hoa tự nhiên',
      'Chống nước IP67',
      'Pin 3-5 ngày',
      'Màu xanh mint dịu mắt',
    ],
  },
  {
    id: 'bunny-pink',
    name: 'ARTEMIS Bunny Green',
    slug: 'bunny-pink',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/templates/bunny-pink.png'],
    specs: {
      waterproof: 'IP67',
      battery: '400mAh - 3-5 ngày',
      gps: true,
      simCard: true,
      weight: '35g',
    },
    description: 'Thỏ hồng pastel đơn giản, nhẹ nhàng và dễ thương nhất. Thiết kế tối giản cho bé yêu thích sự nhẹ nhàng.',
    features: [
      'Định vị GPS/LBS chính xác',
      'Thiết kế Bunny tối giản',
      'Màu sắc pastel nhẹ nhàng',
      'Chống nước IP67',
      'Pin 3-5 ngày',
      'Giá ưu đãi nhất',
    ],
  },
  {
    id: 'necklace-baby-pink',
    name: 'ARTEMIS Dây Chuyền Bunny Baby Pink',
    slug: 'necklace-baby-pink',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/necklaces/necklace-baby-pink.png'],
    specs: {
      waterproof: 'IP67',
      battery: 'N/A',
      gps: false,
      simCard: false,
      weight: '15g',
    },
    description: 'Dây chuyền thỏ hồng baby dễ thương với thiết kế tối giản, phù hợp làm quà tặng hoặc phụ kiện thời trang.',
    features: [
      'Thiết kế Bunny đáng yêu',
      'Chất liệu an toàn cho trẻ',
      'Màu hồng pastel nhẹ nhàng',
      'Dây chuyền inox không gỉ',
      'Mặt pendant chống nước',
      'Giá cả phải chăng',
    ],
  },
  {
    id: 'necklace-pink',
    name: 'ARTEMIS Dây Chuyền Bunny Pink',
    slug: 'necklace-pink',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/necklaces/necklace-pink.png'],
    specs: {
      waterproof: 'IP67',
      battery: 'N/A',
      gps: false,
      simCard: false,
      weight: '15g',
    },
    description: 'Dây chuyền thỏ hồng fuchsia với họa tiết hoa đầy màu sắc, thiết kế vui tươi và năng động.',
    features: [
      'Thiết kế Bunny năng động',
      'Họa tiết hoa đa màu sắc',
      'Màu hồng fuchsia nổi bật',
      'Dây chuyền inox không gỉ',
      'Mặt pendant chống nước',
      'Phù hợp mọi lứa tuổi',
    ],
  },
  {
    id: 'necklace-lavender',
    name: 'ARTEMIS Dây Chuyền Bunny Lavender',
    slug: 'necklace-lavender',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/necklaces/necklace-lavender.png'],
    specs: {
      waterproof: 'IP67',
      battery: 'N/A',
      gps: false,
      simCard: false,
      weight: '15g',
    },
    description: 'Dây chuyền thỏ tím lavender với họa tiết hoa và chấm tròn, phong cách dịu dàng và thanh lịch.',
    features: [
      'Thiết kế Bunny thanh lịch',
      'Họa tiết hoa & chấm tròn',
      'Màu tím lavender trendy',
      'Dây chuyền inox không gỉ',
      'Mặt pendant chống nước',
      'Thời trang và cá tính',
    ],
  },
  {
    id: 'necklace-yellow',
    name: 'ARTEMIS Dây Chuyền Bunny Yellow',
    slug: 'necklace-yellow',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/necklaces/necklace-yellow.png'],
    specs: {
      waterproof: 'IP67',
      battery: 'N/A',
      gps: false,
      simCard: false,
      weight: '15g',
    },
    description: 'Dây chuyền thỏ vàng với họa tiết cà rốt, mang năng lượng tích cực và vui tươi.',
    features: [
      'Thiết kế Bunny vui tươi',
      'Họa tiết cà rốt đáng yêu',
      'Màu vàng cam tươi sáng',
      'Dây chuyền inox không gỉ',
      'Mặt pendant chống nước',
      'Phong cách năng động',
    ],
  },
  {
    id: 'necklace-mint',
    name: 'ARTEMIS Dây Chuyền Bunny Mint',
    slug: 'necklace-mint',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/necklaces/necklace-mint.png'],
    specs: {
      waterproof: 'IP67',
      battery: 'N/A',
      gps: false,
      simCard: false,
      weight: '15g',
    },
    description: 'Dây chuyền thỏ xanh mint với họa tiết hoa và lá tự nhiên, tươi mát và dễ chịu.',
    features: [
      'Thiết kế Bunny tự nhiên',
      'Họa tiết hoa & lá cây',
      'Màu xanh mint dịu mắt',
      'Dây chuyền inox không gỉ',
      'Mặt pendant chống nước',
      'Phong cách thanh lịch',
    ],
  },
  {
    id: 'clip-baby-pink',
    name: 'ARTEMIS Pin Kẹp Bunny Baby Pink',
    slug: 'clip-baby-pink',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/clips/clip-baby-pink.png'],
    specs: {
      waterproof: 'IP67',
      battery: 'N/A',
      gps: false,
      simCard: false,
      weight: '12g',
    },
    description: 'Pin kẹp thỏ hồng baby dễ thương, kẹp lên quần áo, ba lô hoặc mũ. Thiết kế an toàn cho trẻ.',
    features: [
      'Thiết kế Bunny đáng yêu',
      'Kẹp chắc chắn, an toàn',
      'Màu hồng pastel nhẹ nhàng',
      'Chất liệu không độc hại',
      'Dễ dàng tháo lắp',
      'Phù hợp làm phụ kiện',
    ],
  },
  {
    id: 'clip-pink',
    name: 'ARTEMIS Pin Kẹp Bunny Pink',
    slug: 'clip-pink',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/clips/clip-pink.png'],
    specs: {
      waterproof: 'IP67',
      battery: 'N/A',
      gps: false,
      simCard: false,
      weight: '12g',
    },
    description: 'Pin kẹp thỏ hồng fuchsia với họa tiết hoa và tim đầy màu sắc, vui tươi và năng động.',
    features: [
      'Thiết kế Bunny năng động',
      'Họa tiết hoa & tim đáng yêu',
      'Màu hồng fuchsia nổi bật',
      'Kẹp chắc chắn, an toàn',
      'Chất liệu không độc hại',
      'Phù hợp làm phụ kiện',
    ],
  },
  {
    id: 'clip-lavender',
    name: 'ARTEMIS Pin Kẹp Bunny Lavender',
    slug: 'clip-lavender',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/clips/clip-lavender.png'],
    specs: {
      waterproof: 'IP67',
      battery: 'N/A',
      gps: false,
      simCard: false,
      weight: '12g',
    },
    description: 'Pin kẹp thỏ tím lavender với họa tiết hoa đa màu, phong cách dịu dàng và thanh lịch.',
    features: [
      'Thiết kế Bunny thanh lịch',
      'Họa tiết hoa đa màu sắc',
      'Màu tím lavender trendy',
      'Kẹp chắc chắn, an toàn',
      'Chất liệu không độc hại',
      'Thời trang và cá tính',
    ],
  },
  {
    id: 'clip-yellow',
    name: 'ARTEMIS Pin Kẹp Bunny Yellow',
    slug: 'clip-yellow',
    priceFrom: 550000,
    originalPrice: null,
    hasEngraving: false,
    defaultEngravingText: null,
    images: ['/images/clips/clip-yellow.png'],
    specs: {
      waterproof: 'IP67',
      battery: 'N/A',
      gps: false,
      simCard: false,
      weight: '12g',
    },
    description: 'Pin kẹp thỏ vàng với họa tiết cà rốt, mang năng lượng tích cực và vui tươi.',
    features: [
      'Thiết kế Bunny vui tươi',
      'Họa tiết cà rốt đáng yêu',
      'Màu vàng cam tươi sáng',
      'Kẹp chắc chắn, an toàn',
      'Chất liệu không độc hại',
      'Phong cách năng động',
    ],
  },
]

// Cache products for 5 minutes
export const revalidate = 300 // 5 minutes in seconds

export async function GET() {
  return NextResponse.json(MOCK_PRODUCTS)
}
